name: Continuous delivery - Linux

on:
  release:
    types: [published, unpublished]

env:
  FLIT_ROOT_INSTALL: 1

jobs:
  build-onefile:
    name: Build onefile
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install required packages
        run: |
          apt update
          apt install -y binutils
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install flit
          flit install --symlink
      - name: Build
        run: |
          . venv/bin/activate
          pyinstaller ci-scripts/linux/pyinstaller/nitrokey-app-onefile.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nitrokey-app-onefile
          path: |
            dist/nitrokey-app-onefile
  publish-binary:
    name: Publish binary
    runs-on: ubuntu-latest
    container: python:3.9-slim
    needs: build-onefile
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nitrokey-app-onefile
      - name: Rename binary
        run: mv nitrokey-app-onefile nitrokey-app-x64-${{ github.event.release.tag_name }}
      - name: Create archive
        run: tar -czvf nitrokey-app-${{ github.event.release.tag_name }}-linux-x64-binary.tar.gz nitrokey-app-x64-${{ github.event.release.tag_name }}
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: nitrokey-app-${{ github.event.release.tag_name }}-linux-x64-binary.tar.gz