name: Continuous delivery - Windows

on:
  release:
    types: [published, unpublished]

env:
  FLIT_ROOT_INSTALL: 1

jobs:
  build-onefile:
    name: Build onefile
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          .\venv\Scripts\pip install pip
          .\venv\Scripts\pip install flit
          .\venv\Scripts\flit install --symlink
      - name: Build onefile
        run: |
          .\venv\Scripts\Activate.ps1
          pyinstaller ci-scripts/windows/pyinstaller/nitrokey-app-onefile.spec
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nitrokey-app-onefile
          path: |
            dist/nitrokey-app.exe
  publish-binary:
    name: Publish binary
    runs-on: windows-latest
    needs: build-onefile
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nitrokey-app-onefile
      - name: Rename binary
        run: mv nitrokey-app.exe nitrokey-app-x64-${{ github.event.release.tag_name }}.exe
      - name: Create archive
        run: 7z a -tzip -mx9 nitrokey-app-${{ github.event.release.tag_name }}-windows-x64-binary.zip nitrokey-app-x64-${{ github.event.release.tag_name }}.exe
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: nitrokey-app-${{ github.event.release.tag_name }}-windows-x64-binary.zip